# permissions for end users to view rdspostgres.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: rdspostgres-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: go-db-operator
    app.kubernetes.io/part-of: go-db-operator
    app.kubernetes.io/managed-by: kustomize
  name: rdspostgres-viewer-role
rules:
- apiGroups:
  - postgresql.rdsoperator.com
  resources:
  - rdspostgres
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - postgresql.rdsoperator.com
  resources:
  - rdspostgres/status
  verbs:
  - get
